Repository JamminTeam/Jamrello, pull requests merged in 2023-12, with the labels that each got.

#32 Email, 회원가입, 로그아웃핸들러, 내 정보 조회 구현 , 코드리뷰 수정사항 수정
  src/main/java/com/sparta/jamrello/JamrelloApplication.java
  src/main/java/com/sparta/jamrello/domain/board/entity/Board.java
  src/main/java/com/sparta/jamrello/domain/member/controller/MemberController.java
  src/main/java/com/sparta/jamrello/domain/member/dto/EmailRequestDto.java
  src/main/java/com/sparta/jamrello/domain/member/dto/LoginRequestDto.java
  src/main/java/com/sparta/jamrello/domain/member/dto/MemberResponseDto.java
  src/main/java/com/sparta/jamrello/domain/member/dto/SignupRequestDto.java
  src/main/java/com/sparta/jamrello/domain/member/repository/MemberRepository.java
  src/main/java/com/sparta/jamrello/domain/member/repository/entity/Member.java
  src/main/java/com/sparta/jamrello/domain/member/repository/entity/MemberRepository.java
  src/main/java/com/sparta/jamrello/domain/member/service/MemberService.java
  src/main/java/com/sparta/jamrello/domain/member/service/MemberServiceImpl.java
  src/main/java/com/sparta/jamrello/global/config/EmailConfig.java
  src/main/java/com/sparta/jamrello/global/config/RedisConfig.java
  src/main/java/com/sparta/jamrello/global/config/WebSecurityConfig.java
  src/main/java/com/sparta/jamrello/global/constant/ResponseCode.java
  src/main/java/com/sparta/jamrello/global/dto/BaseResponse.java
  src/main/java/com/sparta/jamrello/global/exception/ErrorCode.java
  src/main/java/com/sparta/jamrello/global/exception/ExceptionAdviceController.java
  src/main/java/com/sparta/jamrello/global/exception/ExceptionResponseDto.java
  src/main/java/com/sparta/jamrello/global/security/CustomLogoutHandler.java
  src/main/java/com/sparta/jamrello/global/security/JwtAuthorizationFilter.java
  src/main/java/com/sparta/jamrello/global/security/UserDetailsServiceImpl.java
  src/main/java/com/sparta/jamrello/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/sparta/jamrello/global/security/jwt/JwtAuthorizationFilter.java
  src/main/java/com/sparta/jamrello/global/security/jwt/JwtUtil.java
  src/main/java/com/sparta/jamrello/global/security/jwt/RefreshToken.java
  src/main/java/com/sparta/jamrello/global/security/jwt/RefreshTokenRepository.java
  src/main/java/com/sparta/jamrello/global/utils/EmailService.java
  src/main/java/com/sparta/jamrello/global/utils/RedisService.java
  src/main/resources/application.properties
  src/test/java/com/sparta/jamrello/domain/member/controller/MemberControllerTest.java
Labels: enhancement

#30 #10 feat : [카드상세] 카드 댓글 달기
  src/main/java/com/sparta/jamrello/domain/card/repository/CardRepository.java
  src/main/java/com/sparta/jamrello/domain/card/repository/entity/Card.java
  src/main/java/com/sparta/jamrello/domain/comment/controller/CommentController.java
  src/main/java/com/sparta/jamrello/domain/comment/dto/CommentRequestDto.java
  src/main/java/com/sparta/jamrello/domain/comment/dto/CommentResponseDto.java
  src/main/java/com/sparta/jamrello/domain/comment/repository/CommentRepository.java
  src/main/java/com/sparta/jamrello/domain/comment/repository/entity/Comment.java
  src/main/java/com/sparta/jamrello/domain/comment/service/CommentService.java
  src/main/java/com/sparta/jamrello/domain/comment/service/CommentServiceImplV1.java
  src/main/java/com/sparta/jamrello/domain/member/repository/entity/Member.java
  src/main/resources/application-test.properties
  src/test/java/com/sparta/jamrello/domain/comment/controller/CommentControllerTest.java
  src/test/java/com/sparta/jamrello/domain/comment/repository/CommentRepositoryTest.java
  src/test/java/com/sparta/jamrello/domain/comment/repository/entity/CommentTest.java
  src/test/java/com/sparta/jamrello/domain/comment/service/CommentServiceImplV1Test.java
Labels: feature

#37 Test/card detail
  src/test/java/com/sparta/jamrello/domain/comment/service/CommentServiceImplTestIntegration.java
  src/test/java/com/sparta/jamrello/domain/comment/service/CommentServiceImplV1Test.java
Labels: test

#34 Feature/card
  src/main/java/com/sparta/jamrello/domain/card/Service/CardService.java
  src/main/java/com/sparta/jamrello/domain/card/Service/CardServiceImplV1.java
  src/main/java/com/sparta/jamrello/domain/card/controller/CardController.java
  src/main/java/com/sparta/jamrello/domain/card/dto/CardRequestDto.java
  src/main/java/com/sparta/jamrello/domain/card/dto/request/CardCatalogRequestDto.java
  src/main/java/com/sparta/jamrello/domain/card/dto/request/CardPositionRequestDto.java
  src/main/java/com/sparta/jamrello/domain/card/dto/request/CardRequestDto.java
  src/main/java/com/sparta/jamrello/domain/card/dto/response/CardResponseDto.java
  src/main/java/com/sparta/jamrello/domain/card/repository/CardRepository.java
  src/main/java/com/sparta/jamrello/domain/card/repository/CardRepositoryQuery.java
  src/main/java/com/sparta/jamrello/domain/card/repository/CardRepositoryQueryImpl.java
  src/main/java/com/sparta/jamrello/domain/card/repository/entity/Card.java
  src/main/java/com/sparta/jamrello/domain/cardCollaborators/dto/CardCollaboratorRequestDto.java
  src/main/java/com/sparta/jamrello/domain/cardCollaborators/dto/CardCollaboratorResponseDto.java
  src/main/java/com/sparta/jamrello/domain/cardCollaborators/repository/CardCollaboratorRepository.java
  src/main/java/com/sparta/jamrello/domain/cardCollaborators/repository/entity/CardCollaborator.java
  src/main/java/com/sparta/jamrello/domain/catalog/repository/entity/Catalog.java
  src/main/java/com/sparta/jamrello/domain/catalog/service/CatalogServiceImplV1.java
  src/main/java/com/sparta/jamrello/domain/member/repository/entity/Member.java
  src/main/java/com/sparta/jamrello/global/config/RedisConfig.java
  src/main/java/com/sparta/jamrello/global/exception/ErrorCode.java
  src/main/java/com/sparta/jamrello/global/security/jwt/JwtAuthenticationFilter.java
  src/main/resources/application-test.properties
  src/main/resources/application.properties
  src/test/java/com/sparta/jamrello/domain/card/Service/CardServiceImplV1IntegrationTest.java
  src/test/java/com/sparta/jamrello/domain/comment/repository/CommentRepositoryTest.java
  src/test/java/com/sparta/jamrello/domain/comment/repository/entity/CommentTest.java
Labels: feature

#44 fix 브랜치내 머지오류로 브래친 변경 및 conflict 수정, #20, #35 member 내 정보 수정, 회원 탈퇴 구현
  src/main/java/com/sparta/jamrello/domain/board/controller/BoardController.java
  src/main/java/com/sparta/jamrello/domain/card/controller/CardController.java
  src/main/java/com/sparta/jamrello/domain/card/dto/response/CardResponseDto.java
  src/main/java/com/sparta/jamrello/domain/card/repository/entity/Card.java
  src/main/java/com/sparta/jamrello/domain/member/controller/MemberController.java
  src/main/java/com/sparta/jamrello/domain/member/dto/DeleteMemberRequestDto.java
  src/main/java/com/sparta/jamrello/domain/member/dto/UpdateMemberRequestDto.java
  src/main/java/com/sparta/jamrello/domain/member/repository/MemberRepository.java
  src/main/java/com/sparta/jamrello/domain/member/repository/entity/Member.java
  src/main/java/com/sparta/jamrello/domain/member/service/MemberService.java
  src/main/java/com/sparta/jamrello/domain/member/service/MemberServiceImpl.java
  src/main/java/com/sparta/jamrello/global/constant/ResponseCode.java
  src/main/java/com/sparta/jamrello/global/exception/ErrorCode.java
  src/main/java/com/sparta/jamrello/global/exception/ExceptionAdviceController.java
  src/main/java/com/sparta/jamrello/global/scheduler/Scheduler.java
  src/main/java/com/sparta/jamrello/global/security/CustomLogoutHandler.java
  src/main/java/com/sparta/jamrello/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/sparta/jamrello/global/security/jwt/JwtAuthorizationFilter.java
  src/main/java/com/sparta/jamrello/global/utils/RedisService.java
  src/main/resources/application.properties
  src/test/java/com/sparta/jamrello/domain/member/repository/MemberRepositoryTest.java
Labels: enhancement, feature

#48 #11 feat : card
  src/main/java/com/sparta/jamrello/domain/card/Service/CardService.java
  src/main/java/com/sparta/jamrello/domain/card/Service/CardServiceImplV1.java
  src/main/java/com/sparta/jamrello/domain/card/controller/CardController.java
  src/main/java/com/sparta/jamrello/domain/card/dto/request/CardDuedateRequestDto.java
  src/main/java/com/sparta/jamrello/domain/card/repository/entity/Card.java
  src/test/java/com/sparta/jamrello/domain/card/Service/CardServiceImplV1IntegrationTest.java
Labels: feature

#49 Fix : member
  src/main/java/com/sparta/jamrello/domain/member/controller/MemberController.java
  src/main/java/com/sparta/jamrello/domain/member/repository/entity/Member.java
  src/main/java/com/sparta/jamrello/domain/member/service/MemberServiceImpl.java
Labels: bug
